name: 'rustom'

services:
  mongodb:
    image: mongo:4.4
    platform: linux/arm64
    container_name: rustom_mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env.production
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=1
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: rustom_redis
    command: ["sh", "-c", "redis-server $${REDIS_PASSWORD:+--requirepass \"$$REDIS_PASSWORD\"}"]
    env_file:
      - .env.production
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "if [ -z \"$$REDIS_PASSWORD\" ]; then redis-cli ping; else redis-cli -a \"$$REDIS_PASSWORD\" ping; fi"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rustom_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.production
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  api:
    image: hmtanbir/rustom-mongo:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rustom-api
    ports:
      - "${PORT}:3000"
    env_file:
      - .env.production
    environment:
      - MONGO_HOST=mongodb
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      mongodb:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data:

networks:
  default:
    name: "rustom-mongo"
    driver: bridge